
F = FileWriter()

F['CacheTime']			= '{0}'.format(now()).replace('.', '')

# Init the data
F['InstancePath']		= Instance.Path
F['DevLevel']			= Instance.DevLevel
F['DevName']			= Instance.DevName

F['ProjectIdentifier']	= Project.ID
F['ProjectPath']		= Project.Path

F['Database']			= Project.MySQL

F['FileServer_Host']	= Project.OtherData['FileServer_Host']
F['FileServer_Database']= Project.OtherData['FileServer_Database']

F['URL_HTTP']			= Project.OtherData['URL_HTTP']
F['URL_HTTPS']			= Project.OtherData['URL_HTTPS']

F['JM_Username'] = Project.OtherData['JM_Username']
F['JM_Password'] = Project.OtherData['JM_Password']

# Python needs to read it
F.Write('AutoConf/Local.py', """
# Generated by AutoConf system

from AppStruct.Util import aadict

InstancePath = {InstancePath}
DevLevel = {DevLevel}
DevName = {DevName}

Identifier = {ProjectIdentifier};
Path = {ProjectPath};

Database = {Database}

FileServer = aadict()
FileServer.Host = {FileServer_Host}
FileServer.Database = {FileServer_Database}

URL_HTTP = {URL_HTTP}
URL_HTTPS = {URL_HTTPS}

CacheTime = str({CacheTime})
  
JM_Username = {JM_Username}
JM_Password = {JM_Password}
  

""")


